name: auto update Koala-Hacker-News

on:
  schedule:
    - cron: '0 4 * * MON'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.12]

    steps:
    
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
      with:
        version: 7.17.0
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm build

    