name: auto update Koala-Hacker-News

on:
  schedule:
    - cron: '10 15 * * MON'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.AUTO_COMMIT }}
        
    - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
      with:
        version: 7.17.0
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm build

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: './README.md ./Hacker-News/*.md ./src/data/data.json'
        commit_message: update Koala Hacker News by github-action-bot.
